spring.application.name=DocGuard
spring.datasource.url=jdbc:postgresql://ep-billowing-butterfly-ac0c3gns-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_RH1XxriK7Wqm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true